# WSL distribution metadata for install and first-run setup.
[oobe]
command=/etc/oobe.sh
defaultUid=1000
defaultName=fedora-rawhide

[shortcut]
enabled=false

[windowsterminal]
enabled=true
ProfileTemplate=/usr/lib/wsl/terminal-profile.json
